name: "DocToc"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'README.md'
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  doctoc:
    name: Run DocToc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install DocToc
      run: npm i -g doctoc

    - name: Run DocToc
      run: yarn doctoc
   
    - name: Commit Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Samuel Corsi-House
        author_email: chouse.samuel@gmail.com
        message: 'Update README.md TOC'
        add: 'README.md'
