name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Git Fetch
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install Dependencies
        run: yarn --silent --frozen-lockfile

      - name: Run Linter
        run: yarn nx workspace-lint --fix && yarn nx affected -- --target=lint --base=origin/master --fix

  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Git Fetch
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install Dependencies
        run: yarn --silent --frozen-lockfile

      - name: Run Tests
        run: yarn nx affected --target=test --base=origin/master --codeCoverage --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
